import type { Product, Category, Brand } from './supabase'

export const demoCategories: Category[] = [
  { id: 'c1', name: 'Protein', name_fr: 'Protéine', slug: 'protein', image_url: null, display_order: 1, is_active: true },
  { id: 'c2', name: 'Creatine', name_fr: 'Créatine', slug: 'creatine', image_url: null, display_order: 2, is_active: true },
  { id: 'c3', name: 'Vitamins', name_fr: 'Vitamines', slug: 'vitamins', image_url: null, display_order: 3, is_active: true },
  { id: 'c4', name: 'Mass Gainer', name_fr: 'Prise de masse', slug: 'mass-gainer', image_url: null, display_order: 4, is_active: true },
  { id: 'c5', name: 'Fat Burner', name_fr: 'Brûle-graisses', slug: 'fat-burner', image_url: null, display_order: 5, is_active: true },
  { id: 'c6', name: 'Pre-Workout', name_fr: 'Pré-entraînement', slug: 'pre-workout', image_url: null, display_order: 6, is_active: true },
  { id: 'c7', name: 'BCAA', name_fr: 'BCAA', slug: 'bcaa', image_url: null, display_order: 7, is_active: true },
  { id: 'c8', name: 'Accessories', name_fr: 'Accessoires', slug: 'accessories', image_url: null, display_order: 8, is_active: true },
]

export const demoBrands: Brand[] = [
  { id: 'b1', name: 'Optimum Nutrition', slug: 'on', logo_url: null, is_active: true },
  { id: 'b2', name: 'Dymatize', slug: 'dymatize', logo_url: null, is_active: true },
  { id: 'b3', name: 'MuscleTech', slug: 'muscletech', logo_url: null, is_active: true },
  { id: 'b4', name: 'BioTechUSA', slug: 'biotechusa', logo_url: null, is_active: true },
  { id: 'b5', name: 'OstroVit', slug: 'ostrovit', logo_url: null, is_active: true },
]

export const demoProducts: Product[] = [
  {
    id: 'p1', name: 'Whey Protein Gold Standard', name_fr: 'Whey Protéine Gold Standard',
    slug: 'whey-protein-gold-standard',
    description: 'بروتين واي عالي الجودة من Optimum Nutrition، مثالي لبناء العضلات وما بعد التمرين. يحتوي على 24 جرام بروتين لكل وجبة.',
    description_fr: 'Whey protéine haute qualité d\'Optimum Nutrition, idéale pour la construction musculaire et la récupération post-entraînement.',
    details: '24g بروتين لكل وجبة | 5.5g BCAA | 4g Glutamine | منخفض الكربوهيدرات والدهون',
    usage_instructions: 'أخلط 1 كوب (30g) مع 180-240ml ماء أو حليب بعد التمرين مباشرة، أو في أي وقت آخر من اليوم لتلبية احتياجاتك البروتينية.',
    price: 4500, compare_price: 5500, quantity: 25,
    is_available: true, is_featured: true, is_best_seller: true, is_hidden: false,
    category_id: 'c1', brand_id: 'b1',
    flavors: ['Double Rich Chocolate', 'Vanilla Ice Cream', 'Strawberry', 'Banana'],
    sizes: ['1kg (33 serv)', '2kg (66 serv)', '5lbs (74 serv)'],
    tags: ['بروتين', 'واي', 'عضلات'],
    sales_count: 142, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    product_images: [{ id: 'i1', product_id: 'p1', url: 'https://images.unsplash.com/photo-1617718956199-a1440a7d52b3?w=500&q=85', alt_text: 'Whey Protein', display_order: 0, is_primary: true }],
  },
  {
    id: 'p2', name: 'Creatine Monohydrate 300g', name_fr: 'Créatine Monohydrate 300g',
    slug: 'creatine-monohydrate-300g',
    description: 'كرياتين مونوهيدرات 100% نقي لزيادة القوة والطاقة. مجرَّب ومثبت علمياً لتحسين الأداء الرياضي.',
    description_fr: 'Créatine monohydrate 100% pure pour augmenter la force et l\'énergie. Prouvé scientifiquement pour améliorer les performances sportives.',
    details: '5g كرياتين نقي لكل وجبة | 60 حصة | Micronized للامتصاص السريع | خالٍ من الإضافات',
    usage_instructions: '5 جرام يومياً مع الماء أو عصير قبل أو بعد التمرين. في مرحلة التحميل: 20g يومياً لمدة 5 أيام.',
    price: 2800, compare_price: null, quantity: 18,
    is_available: true, is_featured: false, is_best_seller: true, is_hidden: false,
    category_id: 'c2', brand_id: 'b4',
    flavors: ['Unflavored'],
    sizes: ['300g (60 serv)', '500g (100 serv)'],
    tags: ['كرياتين', 'قوة', 'طاقة'],
    sales_count: 98, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    product_images: [{ id: 'i2', product_id: 'p2', url: 'https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=500&q=85', alt_text: 'Creatine', display_order: 0, is_primary: true }],
  },
  {
    id: 'p3', name: 'Mass Gainer Extreme 3kg', name_fr: 'Mass Gainer Extrême 3kg',
    slug: 'mass-gainer-extreme-3kg',
    description: 'ماس جينر عالي السعرات لزيادة الوزن وبناء الكتلة العضلية بسرعة. مثالي للأشخاص النحيفين.',
    description_fr: 'Mass gainer hypercalorique pour une prise de poids et de masse musculaire rapide. Idéal pour les personnes maigres.',
    details: '75g كربوهيدرات + 30g بروتين لكل وجبة | 1250 سعرة حرارية | فيتامينات ومعادن مضافة',
    usage_instructions: 'وجبة كاملة بين التمارين أو قبل النوم. أخلط 3 أكواب (150g) مع 400ml حليب.',
    price: 6500, compare_price: 7500, quantity: 12,
    is_available: true, is_featured: true, is_best_seller: false, is_hidden: false,
    category_id: 'c4', brand_id: 'b3',
    flavors: ['Chocolate', 'Vanilla', 'Strawberry'],
    sizes: ['3kg (20 serv)', '5kg (33 serv)'],
    tags: ['ماس جينر', 'زيادة الوزن'],
    sales_count: 55, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    product_images: [{ id: 'i3', product_id: 'p3', url: 'https://images.unsplash.com/photo-1584863231364-2edc166de576?w=500&q=85', alt_text: 'Mass Gainer', display_order: 0, is_primary: true }],
  },
  {
    id: 'p4', name: 'Pre-Workout Extreme', name_fr: 'Pré-entraînement Extreme',
    slug: 'pre-workout-extreme',
    description: 'قبل التمرين قوي لتضخيم الطاقة والتركيز والمضخة العضلية. تركيبة علمية متطورة.',
    description_fr: 'Pré-workout puissant pour booster l\'énergie, la concentration et la pump musculaire.',
    details: 'Caffeine 200mg | Beta-Alanine 3.2g | L-Citrulline 6g | L-Arginine 3g | B-Vitamins',
    usage_instructions: 'كوب واحد (10g) مع 200ml ماء 20-30 دقيقة قبل التمرين. لا تتجاوز وجبة واحدة يومياً.',
    price: 3200, compare_price: 3800, quantity: 20,
    is_available: true, is_featured: false, is_best_seller: false, is_hidden: false,
    category_id: 'c6', brand_id: 'b3',
    flavors: ['Fruit Punch', 'Watermelon', 'Blue Raspberry', 'Green Apple'],
    sizes: ['300g (30 serv)'],
    tags: ['pre-workout', 'طاقة', 'تركيز'],
    sales_count: 67, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    product_images: [{ id: 'i4', product_id: 'p4', url: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500&q=85', alt_text: 'Pre-Workout', display_order: 0, is_primary: true }],
  },
  {
    id: 'p5', name: 'BCAA 8000 Amino Acids', name_fr: 'BCAA 8000 Acides Aminés',
    slug: 'bcaa-8000',
    description: 'أحماض أمينية متشعبة بنسبة 2:1:1 لمنع الهدم العضلي وتسريع الاستشفاء.',
    description_fr: 'Acides aminés ramifiés en ratio 2:1:1 pour prévenir le catabolisme musculaire et accélérer la récupération.',
    details: 'L-Leucine 4g | L-Isoleucine 2g | L-Valine 2g لكل وجبة | خالٍ من السكر',
    usage_instructions: 'وجبة واحدة أثناء التمرين أو بعده مباشرة مع الماء.',
    price: 2500, compare_price: null, quantity: 0,
    is_available: false, is_featured: false, is_best_seller: false, is_hidden: false,
    category_id: 'c7', brand_id: 'b4',
    flavors: ['Orange', 'Green Apple', 'Watermelon'],
    sizes: ['300g (30 serv)', '500g (50 serv)'],
    tags: ['BCAA', 'أحماض أمينية', 'استشفاء'],
    sales_count: 31, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    product_images: [{ id: 'i5', product_id: 'p5', url: 'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=500&q=85', alt_text: 'BCAA', display_order: 0, is_primary: true }],
  },
  {
    id: 'p6', name: 'Fat Burner Pro 120 caps', name_fr: 'Brûle-Graisses Pro 120 caps',
    slug: 'fat-burner-pro',
    description: 'حارق دهون قوي للتنشيف والحصول على جسم مفتول. يزيد الحرق وينشط الأيض.',
    description_fr: 'Brûleur de graisses puissant pour la sèche. Augmente la thermogenèse et active le métabolisme.',
    details: 'L-Carnitine 500mg | Green Tea Extract 400mg | CLA 1000mg | Caffeine 100mg لكل كبسولة',
    usage_instructions: 'كبسولتان مع وجبة الصباح وكبسولتان مع وجبة الظهيرة. لا تأخذها قبل النوم.',
    price: 3800, compare_price: 4200, quantity: 15,
    is_available: true, is_featured: true, is_best_seller: false, is_hidden: false,
    category_id: 'c5', brand_id: 'b5',
    flavors: null,
    sizes: ['60 caps', '120 caps'],
    tags: ['حرق دهون', 'تنشيف', 'أيض'],
    sales_count: 44, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    product_images: [{ id: 'i6', product_id: 'p6', url: 'https://images.unsplash.com/photo-1579722822693-d82ad16e9a64?w=500&q=85', alt_text: 'Fat Burner', display_order: 0, is_primary: true }],
  },
  {
    id: 'p7', name: 'Vitamin D3 + K2 5000IU', name_fr: 'Vitamine D3 + K2 5000IU',
    slug: 'vitamin-d3-k2',
    description: 'تركيبة مثالية لصحة العظام والمناعة وتنظيم الهرمونات. D3 مع K2 للامتصاص الأمثل.',
    description_fr: 'Formule idéale pour la santé osseuse, l\'immunité et la régulation hormonale.',
    details: 'Vitamin D3 5000IU | Vitamin K2 (MK-7) 200mcg | MCT Oil base لكل كبسولة',
    usage_instructions: 'كبسولة واحدة يومياً مع وجبة دهنية لامتصاص أفضل.',
    price: 1800, compare_price: null, quantity: 40,
    is_available: true, is_featured: false, is_best_seller: false, is_hidden: false,
    category_id: 'c3', brand_id: 'b5',
    flavors: null,
    sizes: ['90 caps (3 أشهر)', '180 caps (6 أشهر)'],
    tags: ['فيتامين D', 'مناعة', 'عظام'],
    sales_count: 22, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    product_images: [{ id: 'i7', product_id: 'p7', url: 'https://images.unsplash.com/photo-1550572017-edd951aa8ca6?w=500&q=85', alt_text: 'Vitamin D3', display_order: 0, is_primary: true }],
  },
  {
    id: 'p8', name: 'Omega-3 Fish Oil 1000mg', name_fr: 'Oméga-3 Huile de Poisson 1000mg',
    slug: 'omega-3-fish-oil',
    description: 'أوميغا 3 عالية الجودة مستخرجة من أسماك المحيط العميق. لصحة القلب والمفاصل والدماغ.',
    description_fr: 'Oméga-3 de haute qualité extrait de poissons des eaux profondes. Pour la santé cardiaque, articulaire et cérébrale.',
    details: 'EPA 300mg | DHA 200mg لكل كبسولة | مصدر أسماك نقية | خالٍ من الزئبق',
    usage_instructions: '2-3 كبسولات يومياً مع الوجبات.',
    price: 1500, compare_price: null, quantity: 3,
    is_available: true, is_featured: false, is_best_seller: false, is_hidden: false,
    category_id: 'c3', brand_id: 'b1',
    flavors: null,
    sizes: ['90 softgels', '180 softgels'],
    tags: ['أوميغا 3', 'قلب', 'مفاصل'],
    sales_count: 18, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    product_images: [{ id: 'i8', product_id: 'p8', url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&q=85', alt_text: 'Omega 3', display_order: 0, is_primary: true }],
  },
]
